- name: Check to see if the file exists
  ansible.builtin.stat:
    path: "{{ template['destination'] }}"
  register: file_stat

- name: Create the file, if it doesnt exist already or override is set
  ansible.builtin.template:
    src: "{{ template['source'] }}"
    dest: "{{ template['destination'] }}"
  when: not file_stat.stat.exists or template['overwrite']